### ISSUE TITLE
Consider moving to the UBI base images 

### ISSUE THREAD

**Issue by atgreen** [container-lisp/s2i-lisp#10]
We currently have both CentOS and RHEL build support.  Look into switching to the new Red Hat UBI base image instead.

**Comment by hjudt** [comment]
This sounds like a good idea. Especially because the RHEL/CentOS images are rather heavy and take quite a long time building and deploying, compared to other smaller images (like e.g. alpine, which would be great if it had proper gcc support and thus better compatibility).

**Comment by hjudt** [comment]
I have added a preliminary ubi8 Dockerfile for testing to this branch: https://github.com/container-lisp/s2i-lisp/tree/redhat-universal-base-image-8
So far it seems to work and it seems quite a bit smaller than the CentOS7 image, even though I had to make it compile libev instead of installing it because I couldn't find it with yum.

To make it really small, it would of course be better to build it from ubi8 minimal and add needed dependencies (and maybe even s2i-core stuff). Unfortunately, when I started with that I stumbled over some package manager bug that wouldn't let me install git, and after fiddling around with it for some time I finally gave up.

Please test it and if it works, I will merge it; Depending on your test results, we might even consider replacing the existing CentOS image with it.

**Comment by hjudt** [comment]
I have added commits for replacing the other Dockerfiles with the new UBI8 Dockerfile. Now there is no separation between CentOS and RHEL (I've removed RHEL even from the build scripts), but I am not sure whether this is ok with you. Let's see if travis can still build this, then please take a look.

**Comment by atgreen** [comment]
This looks great to me.  Nice work!  I don't see why you shouldn't merge this to master.

**Comment by hjudt** [comment]
I'll do. Apart from resulting in a smaller image, I noticed it also builds a **lot** faster (2-3 instead of 5-6 minutes).

**Comment by hjudt** [comment]
Merged to master.
